# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.hostname = "c2"

  
  # Kubernetes Master Server
  config.vm.define "master2" do |master2|
    master2.vm.box = "bento/ubuntu-18.04"
    master2.vm.hostname = "master2.example.com"
    master2.vm.network "private_network", ip: "172.42.42.110"
    master2.vm.provider "virtualbox" do |v|
      v.name = "master2"
      v.memory = 16384
      v.cpus = 6
    end
    master2.vm.provision "shell", path: "bootstrap_master2.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "worker2#{i}" do |workernode|
      workernode.vm.box = "bento/ubuntu-18.04"
      workernode.vm.hostname = "worker2#{i}.example.com"
      workernode.vm.network "private_network", ip: "172.42.42.11#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "worker2#{i}"
        v.memory = 16384
        v.cpus = 6
      end
      workernode.vm.provision "shell", path: "bootstrap_worker2.sh"
    end
  end

end
